FROM ubuntu:20.04

ARG DEBIAN_FRONTEND=noninteractive

# Install dependencies
RUN apt-get update && apt-get install -y \
    build-essential autotools-dev libpcap-dev \
    libpcre3-dev libpcre2-dev libdumbnet-dev bison flex zlib1g-dev \
    liblzma-dev openssl libssl-dev libnghttp2-dev \
    libhwloc-dev cmake libluajit-5.1-dev libunwind-dev \
    libmnl-dev ethtool libnuma-dev \
    libcurl4-openssl-dev git iproute2 iputils-ping \
    net-tools vim tcpdump && \
    apt-get clean


# Install DAQ and dependencies
WORKDIR /opt
RUN git clone https://github.com/snort3/libdaq.git && \
    cd libdaq && ./bootstrap && ./configure && make && make install

# Install Snort 3
RUN git clone https://github.com/snort3/snort3.git && \
    cd snort3 && ./configure_cmake.sh --prefix=/usr/local && \
    cd build && make -j$(nproc) && make install


# Add Snort to PATH
ENV PATH="/usr/local/bin:$PATH"

CMD ["echo 1 > /proc/sys/net/ipv4/ip_forward"]
RUN echo "/usr/local/lib" > /etc/ld.so.conf.d/snort3.conf && ldconfig


# Run Snort with default configuration
# CMD [ "snort -c /usr/local/etc/snort/snort.lua -i eth0 --plugin-path /usr/local/lib/snort_extra" ]
