FROM ubuntu:22.04

ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update && apt-get install -y \
    curl gnupg lsb-release sudo vim net-tools iputils-ping rsyslog openssh-server \
    && rm -rf /var/lib/apt/lists/*

RUN curl -s https://packages.wazuh.com/key/GPG-KEY-WAZUH | apt-key add - && \
    echo "deb https://packages.wazuh.com/4.x/apt stable main" | tee /etc/apt/sources.list.d/wazuh.list && \
    apt-get update && apt-get install -y wazuh-agent && \
    rm -rf /var/lib/apt/lists/*

RUN mkdir /var/run/sshd && echo 'root:root' | chpasswd
RUN echo "net.ipv4.ip_forward=1" >> /etc/sysctl.conf

EXPOSE 22

CMD service ssh start && tail -f /var/ossec/logs/ossec.log
