FROM ubuntu:24.04

# Noninteractive mode for apt
ENV DEBIAN_FRONTEND=noninteractive

# Update and install basic packages
RUN apt-get update && apt-get install -y \
    sudo \
    openssh-server \
    net-tools \
    iproute2 \
    iputils-ping \
    rsyslog \
    curl \
    wget \
    gnupg \
    nano \
    tcpdump \
    systemctl

# Enable IP forwarding
RUN echo "net.ipv4.ip_forward=1" >> /etc/sysctl.conf

# Instructions: https://documentation.wazuh.com/current/installation-guide/wazuh-agent/wazuh-agent-package-linux.html

# Install the GPG key
RUN curl -s https://packages.wazuh.com/key/GPG-KEY-WAZUH | gpg --no-default-keyring --keyring gnupg-ring:/usr/share/keyrings/wazuh.gpg --import && chmod 644 /usr/share/keyrings/wazuh.gpg

# Add the repository
RUN echo "deb [signed-by=/usr/share/keyrings/wazuh.gpg] https://packages.wazuh.com/4.x/apt/ stable main" | tee -a /etc/apt/sources.list.d/wazuh.list

# Update the package index
RUN apt-get update

# Install Wazuh agent
# Set the Wazuh manager IP address (change this to your actual Wazuh manager IP)
# Note: Replace "<WAZUH_MANAGER_IP>" with your actual Wazuh manager IP
RUN WAZUH_MANAGER="10.0.0.2" apt-get install wazuh-agent

# Enable and start the Wazuh agent service
RUN systemctl daemon-reload && \
    systemctl enable wazuh-agent && \
    systemctl start wazuh-agent

# Disable Wazuh updates
RUN sed -i "s/^deb/#deb/" /etc/apt/sources.list.d/wazuh.list && \
    apt-get update



# SSH setup
RUN mkdir /var/run/sshd && \
    echo 'root:toor' | chpasswd && \
    sed -i 's/#PermitRootLogin prohibit-password/PermitRootLogin yes/' /etc/ssh/sshd_config && \
    sed -i 's/Port 22/Port 2222/' /etc/ssh/sshd_config

# Expose SSH port
EXPOSE 2222

# # Run services
# CMD ["sh", "-c", "sysctl -w net.ipv4.ip_forward=1 && service rsyslog start && service ssh start && suricata -i eth1 -c /etc/suricata/suricata.yaml -D && tail -f /var/log/suricata/fast.log"]

# Run services manually in the foreground
# CMD ["sh", "-c", "sysctl -w net.ipv4.ip_forward=1 && rsyslogd && /usr/sbin/sshd -D && suricata -i eth1 -c /etc/suricata/suricata.yaml -D && tail -f /var/log/suricata/fast.log"]

# Run services manually in the background
CMD ["sh", "-c", "sysctl -w net.ipv4.ip_forward=1 && \
    rsyslogd & \
    /usr/sbin/sshd -D & \
    "
]

