module(load="imuxsock")          # local (container) syslog
module(load="imklog")            # kernel (container)
module(load="imtcp")             # TCP 514
module(load="imudp")             # UDP 514
module(load="imrelp")            # RELP 2514

# Tune queues a bit for lab
$MainMsgQueueType LinkedList
$MainMsgQueueHighWatermark 20000
$MainMsgQueueLowWatermark 15000
$MainMsgQueueDiscardMark 25000
$MainMsgQueueTimeoutEnqueue 0

# Include drop-ins
$IncludeConfig /etc/rsyslog.d/*.conf