FROM ubuntu:24.04

RUN apt-get update && apt-get install -y --no-install-recommends \
      openssh-server \
      squid \
      rsyslog \
      net-tools \
      iproute2 \
      iputils-ping \
      tcpdump \
      vim \
      nano \
      curl \
      wget \
      procps \
      dnsutils \
      nmap \
      netcat-openbsd \
      isc-dhcp-client \
      curl ca-certificates dumb-init && rm -rf /var/lib/apt/lists/*

COPY squid.conf /etc/squid/squid.conf
COPY docker-entrypoint.sh /usr/local/bin/entrypoint.sh

RUN chmod +x /usr/local/bin/entrypoint.sh

RUN mkdir /var/run/sshd && \
    echo 'root:pass' | chpasswd && \
    sed -i 's/^#\?PermitRootLogin.*/PermitRootLogin yes/' /etc/ssh/sshd_config && \
    sed -i 's/^#\?PasswordAuthentication.*/PasswordAuthentication yes/' /etc/ssh/sshd_config && \
    sed -i 's/^#\?UsePAM.*/UsePAM no/' /etc/ssh/sshd_config

RUN mkdir -p /var/spool/squid /var/log/squid && \
    chown -R proxy:proxy /var/spool/squid /var/log/squid /etc/squid

EXPOSE 3128 22
ENTRYPOINT ["/usr/local/bin/entrypoint.sh"]