# Logs to files owned by 'proxy'
cache_log /var/log/squid/cache.log
access_log /var/log/squid/access.log
cache_store_log none

# Reverse proxy port
http_port 3128 accel vhost
# (Optional if your app expects a single host)
# http_port 3128 accel vhost defaultsite=app.example.com

# Allow (lab)
acl localnet src all
http_access allow localnet
http_access deny all

# Do not store to disk
cache deny all
# (optional) cache_mem 128 MB

# Backends (HTTP)
cache_peer 10.10.10.11 parent 80 0 no-query originserver round-robin name=web1
cache_peer 10.10.10.12 parent 80 0 no-query originserver round-robin name=web2
cache_peer_access web1 allow all
cache_peer_access web2 allow all
never_direct allow all