# Dockerfile for iptables in Ubuntu
FROM ubuntu:20.04

ARG DEBIAN_FRONTEND=noninteractive

RUN apt-get update && \
    apt-get install -y --no-install-recommends \
      iptables \
      iproute2 \
      iputils-ping \
      net-tools \
      tcpdump \
      vim \
    && rm -rf /var/lib/apt/lists/*

CMD ["/bin/bash"]
# # Default command keeps container running
# CMD ["tail", "-f", "/dev/null"]
