FROM alpine:latest

# 1. Install packages
# REMOVED: isc-dhcp-client (it does not exist in Alpine anymore)
RUN apk add --no-cache syslog-ng curl net-tools iputils python3 py3-flask bash

# 2. Configure syslog-ng
RUN echo '@version: 4.10' > /etc/syslog-ng/syslog-ng.conf && \
    echo 'options { keep-hostname(yes); };' >> /etc/syslog-ng/syslog-ng.conf && \
    echo 'source s_net { network(transport(udp) port(514)); };' >> /etc/syslog-ng/syslog-ng.conf && \
    echo 'destination d_local { file("/var/log/student.log"); };' >> /etc/syslog-ng/syslog-ng.conf && \
    echo 'log { source(s_net); destination(d_local); };' >> /etc/syslog-ng/syslog-ng.conf

# 3. Create the log file
RUN touch /var/log/student.log && chmod 666 /var/log/student.log

# 4. Expose ports
EXPOSE 514/udp 5000/tcp 80/tcp

# 5. Start Bash (so you can configure IP manually)
CMD ["/bin/bash"]