FROM ubuntu:24.04

ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update && apt-get install -y \
    openssh-server \
    rsyslog \
    iproute2 \
    iputils-ping \
    net-tools \
    tcpdump \
    telnet \
    curl \
    wget \
    git \
    nano \
    vim \
    netcat-openbsd


RUN git clone https://github.com/thiagoralves/OpenPLC_v3.git /opt/OpenPLC_v3

WORKDIR /opt/OpenPLC_v3
RUN ./install.sh docker

EXPOSE 8080
EXPOSE 502
EXPOSE 22

# ENTRYPOINT ["/bin/bash", "/opt/OpenPLC_v3/start_openplc.sh"]
CMD ["sh", "-c", "/opt/OpenPLC_v3/start_openplc.sh"]